version: "3"
services:
    python:
        image: "python:3.9.6"
        container_name: "python_v_3_9"
        networks:
            - python_v_3_9_network
        volumes:
            - ./app:/src/app
            - ./results:/src/results
            - ./sources:/src/sources

volumes:
    python_v_3_9_data:

networks:
    python_v_3_9_network: